version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db_prod
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    build: xopeeek/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    container_name: frontend_prod
    env_file: .env
    build: xopeeek/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    container_name: nginx_prod
    build: xopeeek/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media_volume:/media
